# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a31e51aa73d7ffe6dd1c37ea1bd21cd5ddf44873d6285183139d5b525778b65d14e4893cf1e96c487326eb9df1f7c6d44ae885a357a3ef7e40fd250f97bcefd

test:
  secret_key_base: 757653c22c82076e3c2efce823638239225e43e1ca5c013dbc8e09cf13c4777cae1a03b8c66700d181a2f8f0888c86cc4e930ccf4396315f71a71f98bc2e24ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
